### ISSUE TITLE
"[Enhancement][UI] 메인엑티비티 & 홈프레그먼트 레이아웃 작업"에 잘못된 코드 발견

### ISSUE THREAD

**Issue by SeonghwiShin** [threeo-clock/WeTube#5]
https://github.com/threeo-clock/WeTube/pull/3
애 리뷰남겨두었습니다. 참고후 수정바랍니다.

**Comment by SeonghwiShin** [comment]
Assignees하고싶은데 안되네요... ㅠ

**Comment by joye-seo** [comment]
2개의 fragment를 변수로 지정 후 수정하였습니다!
